- name: Check for existing kubelet configuration
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf

- name: mkdir /etc/kubernetes/pki/
  file: path=/etc/kubernetes/pki/ state=directory

- copy:
    src: /tmp/{{ name }}-master/etc/kubernetes/pki/ca.crt
    dest: /etc/kubernetes/pki/ca.crt
    mode: 0644

- name: kubeadm join
  command: "{{ hostvars[groups.master[0]]['joincommand'] }} --skip-preflight-checks"
  args:
    creates: /etc/kubernetes/kubelet.conf
  when: kubelet_conf.stat.exists == False
